### ISSUE TITLE
InsertCopy and KeepLabels = true results in ArgumentException

### ISSUE THREAD

**Issue by idars** [xBimTeam/XbimEssentials#333]
Hey there!

I'm looking to strip away unnecessary details from IFC files and keep only certain elements such as `IIfcWall` (the exterior ones at least), `IIfcDoor` and `IIfcWindow`. For that, I'm following the steps from https://docs.xbim.net/examples/insert-copy-function.html but things get sketchy when the `KeepLabels` parameter is set to true. For some IFC files, the `InsertCopy` methods throw an exception even though the destination model is created from scratch. Keeping the labels would be beneficial as I also plan to split the IFC files and display several, smaller WexBIM files on demand.

#### Assemblies and versions affected:

Xbim.Essentials 5.1.289

#### Steps (or code) to reproduce the issue:

Using a .NET Framework 4.8 console app:

```csharp
using System;
using System.Linq;
using Xbim.Common;
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;
using Xbim.IO;

namespace Example
{
    class InsertCopy
    {
        static void Main(string[] args)
        {
            const string original = "Test.ifc";
            const string inserted = "Test2.ifc";
            const bool keepLabels = true;

            using (var model = IfcStore.Open(original))
            {
                var products = Array.Empty<IIfcProduct>()
                    .Concat(model.Instances.OfType<IIfcWindow>())
                    .Concat(model.Instances.OfType<IIfcDoor>())
                    .Concat(model.Instances.OfType<IIfcWall>())
                    .Concat(model.Instances.OfType<IIfcRoof>())
                    .Concat(model.Instances.OfType<IIfcSlab>())
                    .Concat(model.Instances.OfType<IIfcBuildingElementProxy>());

                using (var iModel = IfcStore.Create(model.SchemaVersion, XbimStoreType.InMemoryModel))
                {
                    using (var txn = iModel.BeginTransaction())
                    {
                        var map = new XbimInstanceHandleMap(model, iModel);
                        iModel.InsertCopy(products, true, keepLabels, map);
                        txn.Commit();
                    }

                    iModel.SaveAs(inserted);
                }
            }
        }
    }
}
```

#### Minimal file to reproduce the issue:

[Attachment.zip](https://github.com/xBimTeam/XbimEssentials/files/4481502/Attachment.zip)

#### Expected behavior:

InsertCopy does not throw an exception as the model that is inserted into is initially empty.

#### Actual behavior or exception details:

InsertCopy throws the following exception:

```
Xbim.Common.Exceptions.XbimException: General failure in InsertCopy (General failure in InsertCopy (General failure in InsertCopy (An item with the same key has already been added.))) ---> Xbim.Common.Exceptions.XbimException: General failure in InsertCopy (General failure in InsertCopy (An item with the same key has already been added.)) ---> Xbim.Common.Exceptions.XbimException: General failure in InsertCopy (An item with the same key has already been added.) ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xbim.Common.Model.EntityCollection.<>c__DisplayClass30_0.<AddReversible>b__1() in d:\a\1\s\Xbim.Common\Model\EntityCollection.cs:line 275
   at Xbim.Common.Model.Transaction.DoReversibleAction(Action doAction, Action undoAction, IPersistEntity entity, ChangeType changeType, Int32 propertyOrder) in d:\a\1\s\Xbim.Common\Model\Transaction.cs:line 72
   at Xbim.Common.Model.EntityCollection.AddReversible(IPersistEntity entity) in d:\a\1\s\Xbim.Common\Model\EntityCollection.cs:line 285
   at Xbim.Common.Model.EntityCollection.New(Type t, Int32 label) in d:\a\1\s\Xbim.Common\Model\EntityCollection.cs:line 198
   at Xbim.Common.Model.StepModel.<InsertCopy>b__95_0[T](Type type, Int32 i) in d:\a\1\s\Xbim.Common\Model\StepModel.cs:line 686
   at Xbim.Common.ModelHelper.InsertCopy[T](IModel model, T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels, Func`3 getLabeledEntity) in d:\a\1\s\Xbim.Common\ModelHelper.cs:line 380
   --- End of inner exception stack trace ---
   at Xbim.Common.ModelHelper.InsertCopy[T](IModel model, T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels, Func`3 getLabeledEntity) in d:\a\1\s\Xbim.Common\ModelHelper.cs:line 478
   at Xbim.Common.ModelHelper.InsertCopy[T](IModel model, T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels, Func`3 getLabeledEntity) in d:\a\1\s\Xbim.Common\ModelHelper.cs:line 425
   --- End of inner exception stack trace ---
   at Xbim.Common.ModelHelper.InsertCopy[T](IModel model, T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels, Func`3 getLabeledEntity) in d:\a\1\s\Xbim.Common\ModelHelper.cs:line 478
   at Xbim.Common.ModelHelper.InsertCopy[T](IModel model, T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels, Func`3 getLabeledEntity) in d:\a\1\s\Xbim.Common\ModelHelper.cs:line 405
   --- End of inner exception stack trace ---
   at Xbim.Common.ModelHelper.InsertCopy[T](IModel model, T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels, Func`3 getLabeledEntity) in d:\a\1\s\Xbim.Common\ModelHelper.cs:line 478
   at Xbim.Common.Model.StepModel.InsertCopy[T](T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels, Boolean noTransaction) in d:\a\1\s\Xbim.Common\Model\StepModel.cs:line 690
   at Xbim.Common.Model.StepModel.InsertCopy[T](T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels) in d:\a\1\s\Xbim.Common\Model\StepModel.cs:line 657
   at Xbim.Ifc.IfcStore.InsertCopy[T](T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, Boolean includeInverses, Boolean keepLabels) in D:\a\1\s\Xbim.Ifc\IfcStore.cs:line 353
   at Xbim.Ifc.IfcStoreCopyItemsExtensions.InsertCopy(IModel model, IEnumerable`1 products, Boolean includeGeometry, Boolean keepLabels, XbimInstanceHandleMap mappings) in D:\a\1\s\Xbim.Ifc\Extensions\IfcStoreCopyItemsExtensions.cs:line 52
   at Example.InsertCopy.Main(String[] args) in C:\source\repos\Example\InsertCopy.cs:line 33
```

Possibly related: xBimTeam/XbimExchange#30

Maybe I am missing something here?

**Comment by martin1cerny** [comment]
`IfcStore` is maintaining owner history of all `IfcRoot` objects so when you are creating or modifying the file it keeps the owner history right. But when you are inserting entities from other model then this might cause an entity label clash. I have just pushed a fix for this.

**Comment by idars** [comment]
Thank you for fixing this so quickly! Are you able to release this soon, or will it be released at a later time?

**Comment by idars** [comment]
Ah right, should have seen that. I'll give it a try. Thanks!
