### ISSUE TITLE
IFC2x3 to Wexbim Conversion Problem with XBIM 

### ISSUE THREAD

**Issue by ogz** [xBimTeam/XbimEssentials#464]
Hi,
I am trying to integrate XBIM Web UI in to our application.
We have IFC files in the local file system.
We convert these IFC files to WexBIM format to display them in the browser (via XBIM Web UI).
As far as I see XBIMv4 supports IFC versions 2x3 and 4.

But in my case, conversion works correctly with IFC4 files but not with IFC2x3 files.
There is no exception or error message during the process and one WexBIM file created after the conversion.
But the result wexBIM file is only **1KB**.
And nothing is displayed on the browser if we load that wexBIM file to the browser.

#### Assemblies and versions affected:

.net 6 and XBIM.Geometry v5.1.437

#### Steps (or code) to reproduce the issue:

*I just run the following code to perform the conversion*

```csharp
using (var model = GetModel(originalIFCFilePhysicalPath, wexbimDestFolderPath, ref ifcFileName))
{
	if (model == null)
	{
		Logger.Error("No ifc model to process");
		return GenericRequestResultCode.NotFound;
	}
	var context = new Xbim3DModelContext(model);

	context.CreateContext();
	using (var wexBiMfile = new FileStream(wexbimFilePhysicalPath, FileMode.Create, FileAccess.Write))
	{
		using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
		{
			model.SaveAsWexBim(wexBimBinaryWriter);
			wexBimBinaryWriter.Close();
		}
		wexBiMfile.Close();
	}
}
```

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*

#### Expected behavior:

*A valid WexBIM File*

#### Actual behavior or exception details:

*A WecBIM file with size of 1KB*

**Comment by willoftw** [comment]
Hello there,

Could you provide the IFC2x3 file in question? I will see if I can replicate the issue on my end.

Thanks,
Will

**Comment by ogz** [comment]
Hi Will, thank you.
Here is the original file and the result wexBIM file

[test.ifc.zip](https://github.com/xBimTeam/XbimEssentials/files/10085612/test.ifc.zip)
[test.wexbim.zip](https://github.com/xBimTeam/XbimEssentials/files/10085616/test.wexbim.zip)

**Comment by ogz** [comment]
Hi Will,
The example IFC files are in IFC2x3 format and WexBIM files are the results of the conversion.
They are the problematic files.

I didn't uploaded any IFC4 example files because they were converted correctly.

Regards,
Reha

**Comment by willoftw** [comment]
Hi Ogz,

The issue is that the file provided does not adhere to CV-2x3 [().]([](http://standards.buildingsmart.org/documents/Implementation/IFC_Implementation_Agreements/CV-2x3-106.html))

Here is the simple resolution:
![image](https://user-images.githubusercontent.com/2370856/204513819-6ca291fa-f9a4-4654-aa80-13b0387f585f.png)

The reason I ask about the IFC4 example is that this shouldn't change with schema. Maybe it was exported with a different program?

Hope this helps,
Will

**Comment by ogz** [comment]
Hi Will,

Sorry for the late response.
Do you mean I should change the content of the file?
Unfortunately, the file belongs to the customer and we are providing a CMS for the customer.
Therefore I cannot modify the file. In addition, I don't know which program(s) they are using.
The sample file has just been uploaded to the CMS server.
But at least I will test your solution to see if it solves the problem.

Is there anything that I can do with a code change at the backend?
Regards,

Reha

**Comment by ogz** [comment]
Hi Will,
Thank you for your response.
I have tested your solution and it works if I change the content (IFCGEOMETRICREPRESENTATIONSUBCONTEXT) of the IFC file.
But I furthermore have tested another file and there the following lines are missing:

```
IFCGEOMETRICREPRESENTATIONCONTEXT($, 'Plan'.............
IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Body', 'Model', .............
IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Box', 'Model',.............
```

I tried to manually add the lines, but there was no success.
It ended with the following exception during the conversion.

```
Exception during ifc to wexbim conversion: System.NullReferenceException: Object reference not set to an instance of an object.
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.<>c__DisplayClass18_0.<.ctor>b__1(IIfcGeometricRepresentationContext c)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext..ctor(IModel model, String contextType, String requiredContextIdentifier, ILogger logger)
[sample2.zip](https://github.com/xBimTeam/XbimEssentials/files/10228267/sample2.zip)

   at PPMRoom.Services.XBimService.CreateTempWexbimFile(String originalIFCFilePhysicalPath, String wexbimFilePhysicalPath, String wexbimDestFolderPath) in E:\GitLab-Runner\builds\NnDCcrQP\0\ppm-raum\ppm-raum-backend\src\PPMRoom.Services\Services\XBimService.cs:line 155
[2022-12-14 14:27:26.7300 ERROR PPMRoom.Services.XBimService]
```
I have attached the file, do you have any idea about that matter?

Regards,

Reha

**Comment by martin1cerny** [comment]
In this case, geometry representations don't refer to **any context** at all. This is an invalid IFC file, because all subtypes of [IfcRepresentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrepresentation.htm) have to define their context.
