### ISSUE TITLE
AccessViolationException when loading a IFC file

### ISSUE THREAD

**Issue by christianstroh** [xBimTeam/XbimEssentials#532]
*When loading a specific IFC file, a AccessViolationException sporadically occurs.*

#### Assemblies and versions affected:

*Project Xbim.Geometry.Engine in solution Xbim.Geometry.Engine (master branch)*

#### Steps (or code) to reproduce the issue:

*Load a specific ifc file with XbimXplorer.*

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*

#### Expected behavior:

*That no crash occurs ;)*

#### Actual behavior or exception details:

System.AccessViolationException
The exception that is thrown when there is an attempt to read or write protected memory.

StackTrace:
   at BRepOffsetAPI_MakePipeShell.{ctor}(BRepOffsetAPI_MakePipeShell* , TopoDS_Wire* )
   at Xbim.Geometry.XbimSolid.BuildSweptDiskSolid(TopoDS_Wire* directrixWire, Double radius, Double innerRadius, BRepBuilderAPI_TransitionMode transitionMode)
   at Xbim.Geometry.XbimSolid.Init(IIfcSweptDiskSolid solid, ILogger logger)
   at Xbim.Geometry.XbimSolid..ctor(IIfcSweptDiskSolid solid, ILogger logger)
   at Xbim.Geometry.XbimGeometryCreator.CreateSolid(IIfcSweptDiskSolid ifcSolid, ILogger logger)
   at Xbim.Geometry.XbimGeometryCreator.Create(IIfcGeometricRepresentationItem geomRep, IIfcAxis2Placement3D objectLocation, ILogger logger)
   at Xbim.Geometry.Engine.Interop.XbimGeometryEngine.Create(IIfcGeometricRepresentationItem ifcRepresentation, ILogger logger) in C:\Git\BIM\XbimGeometry\Xbim.Geometry.Engine.Interop\XbimGeometryEngine.cs:line 74

**Comment by christianstroh** [comment]
Sorry, wrong repository.
