### ISSUE TITLE
Unable to convert IFC to wexbim

### ISSUE THREAD

**Issue by Dhruti03** [xBimTeam/XbimEssentials#97]
Hello,
I'm facing an exception while converting IFC file to wexbim. I got the exception while parsing the IFC file using IfcStore.Open(fileName) i.e just before creating context. Please find the attached file.
Thanks.
  
 ```

>   System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.Stack`1.Pop()
>    at Xbim.IO.Step21.XbimP21Parser.EndEntity() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\XbimP21Parser.cs:line 206
>    at QUT.Gppg.ShiftReduceParser`2.Reduce(Int32 ruleNumber) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:line 332
>    at QUT.Gppg.ShiftReduceParser`2.Parse() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:line 263
>    at Xbim.IO.Memory.MemoryModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:line 536
>    at Xbim.IO.Memory.MemoryModel.LoadStep21(String file, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:line 550
>    at Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.Ifc\IfcStore.cs:line 362
>    at ePMBeta.Logics.ModelConverter.GetModel(String fileName) in D:\Backup\SampleProject\IFC\ModelConverter.cs:line 81
> 

```

[500 Error upload Columbia PH2_R0.zip](https://github.com/xBimTeam/XbimEssentials/files/1186912/500.Error.upload.Columbia.PH2_R0.zip)

**Comment by martin1cerny** [comment]
I'm sorry but your exception log doesn't contain anything IFC or xBIM
specific. Can you share the file please?

Dne 31. 7. 2017 10:41 napsal uživatel "Dhruti03" <notifications@github.com>:

**Comment by Dhruti03** [comment]
Thanks for the reply. Please find the attached file.

   
  ```

>  System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.Stack`1.Pop()
>    at Xbim.IO.Step21.XbimP21Parser.EndEntity() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\XbimP21Parser.cs:line 206
>    at QUT.Gppg.ShiftReduceParser`2.Reduce(Int32 ruleNumber) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:line 332
>    at QUT.Gppg.ShiftReduceParser`2.Parse() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:line 263
>    at Xbim.IO.Memory.MemoryModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:line 536
>    at Xbim.IO.Memory.MemoryModel.LoadStep21(String file, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:line 550
>    at Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.Ifc\IfcStore.cs:line 362
>    at ePMBeta.Logics.ModelConverter.GetModel(String fileName) in D:\Backup\SampleProject\IFC\ModelConverter.cs:line 81

```


[C_PH2_R0.zip](https://github.com/xBimTeam/XbimEssentials/files/1192959/C_PH2_R0.zip)

**Comment by martin1cerny** [comment]
I just checked and there is no problem in `develop` branch. We did some changes to make parser more tolerant and I think that these changes didn't make it to `master` branch yet.

```cs
[TestMethod]
public void TestParser()
{
    const string file = @"500 Error upload Columbia PH2_R0.ifc";
    using (var model = new MemoryModel(new Ifc2x3.EntityFactory()))
    {
        var errs = model.LoadStep21(file);
        Assert.IsTrue(errs == 0);
    }
}
```

**Comment by martin1cerny** [comment]
It is actually an error in Tekla exporter which puts a TAB in a string which is illegal and should be encoded using defined procedures. We decided to accept this because it doesn't create any ambiguity and xBIM will encode it properly if you open it and save with xBIM. But other tools might crash as well (just checked Solibri and it failed to open the file).

```
#100832= IFCPROPERTYSINGLEVALUE('Preliminary mark',$,IFCLABEL('40-4	'),$);
                                                                     ^
                                                              TAB character
```
